### ISSUE TITLE
correct mistakes in README

### ISSUE THREAD

**Issue by jackhu-bme** [ruotianluo/rtutils#2]
there are something to be clarified:

1) error exists in the use command in README.md
`trainer.pl_patch.patch_everything(trainer)`
should be replaced with
`rtutils.pl_patch.patch_everything(trainer)`

2) import is needed, this should be included in REAME.md
`import rtutils.pl_patch`

3) version clarification
the version of 0.2.2/0.2.1 is only compatiable with pytorch_lightning > 1.3
I previously tried the pytorch_lightning==1.2.9 and bug exists.

**Comment by ruotianluo** [comment]
Thanks!  Would you like to send a PR?

**Comment by jackhu-bme** [comment]
Sure. Let me try.

**Comment by jackhu-bme** [comment]
Pull request is sended, please check if any mistake exists.

**Comment by jackhu-bme** [comment]
Are you interested in merging the pull request?
